version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - task_db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__TaskDbContext: Server=task_db,1433;Database=TaskManagement;User Id=sa;Password=Chani7265!;TrustServerCertificate=True;
      Jwt__Key: THIS_IS_MY_SECRET_KEY_AND_IT_NEEDS_TO_BE_LONG_ENOUGH_32_BYTES
      Jwt__Issuer: TaskManagement
      Jwt__Audience: TaskManagementUsers

  task_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: task_db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Chani7265!
    ports:
      - "1435:1433"
    volumes:
      - sql_data:/var/opt/mssql

  client:
    build: ./client
    ports:
      - "5174:5174"
    depends_on:
      - server
    environment:
      VITE_API_URL: http://localhost:8080

volumes:
  sql_data: