services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5063:8080"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:8080
     - ConnectionStrings__DefaultConnection=Server=localhost, 1434;Database=taskMangement;User Id=SA;Password=Chani,7265;

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - server
    dns:
      - 8.8.8.8
      - 1.1.1.1